### ISSUE TITLE
Segfault in most applications

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#120]
Issue created by migration from Trac.

Original creator: hhecht

Original creation time: 2013-07-28 03:46:05

Assignee: menal

Version: 5.5.0

Built 5.5.0 on linux with gcc 4.7.1; builds fine, "make test" gives no errors but a handful of warnings I can't interpret.  Running the command line solver as suggested in INSTALL seems to work.

However, when trying to run e.g. the match application, it segfaults.  BT:
#0  0x0804bffe in user_find_cuts (user=0x0, varnum=6, iter_num=1, level=0,
    index=0, objval=3, indices=0x9d5d4b8, values=0x9d5d5b0,
    ub=4.0000001999999997, etol=9.9999999999999995e-08, num_cuts=0x9d58d08,
    alloc_cuts=0x9d58d10, cuts=0x9d58d0c)
    at /home/test/vrp/SYMPHONY-5.5.0/SYMPHONY/Applications/MATCH/src/CutGen/user_cg.c:93
#1  0x080cf94f in find_cuts_u (p=0x9d58ca0, lp_data=0x9d5c7b8,
    num_cuts=0xbfe2baf0) at CutGen/cg_wrapper.c:85
#2  0x080afe21 in generate_cuts_in_lp_u (p=0x9d596c0) at LP/lp_wrapper.c:2465
#3  0x080a5807 in receive_cuts (p=0x9d596c0, first_lp=1, no_more_cuts_count=0)
    at LP/lp_proccomm.c:371
#4  0x0809b31d in fathom_branch (p=0x9d596c0) at LP/lp_genfunc.c:536
#5  0x0809a644 in process_chain (p=0x9d596c0) at LP/lp_genfunc.c:187
#6  0x08088006 in solve (tm=0x9d58d88) at TreeManager/tm_func.c:405
#7  0x0804ed86 in sym_solve (env=0x9d5b290) at Master/master.c:1265
#8  0x080bf692 in lbranching_search (p=0x9d38af0, solutionValue=0xbfe2c0f8,
    colSolution=0x9d3d768, betterSolution=0x9d3d6e8, t_lb=3)
    at LP/lp_heuristics.c:3683
#9  0x080ac97d in is_feasible_u (p=0x9d38af0, branching=0 '\000',
    is_last_iter=0 '\000') at LP/lp_wrapper.c:1093
#10 0x0809b1c3 in fathom_branch (p=0x9d38af0) at LP/lp_genfunc.c:493
#11 0x0809a644 in process_chain (p=0x9d38af0) at LP/lp_genfunc.c:187
#12 0x08088006 in solve (tm=0x9d381b8) at TreeManager/tm_func.c:405
#13 0x0804ed86 in sym_solve (env=0x9d36420) at Master/master.c:1265
#14 0x0804aeb5 in main (argc=3, argv=0xbfe2c574)
    at /home/test/vrp/SYMPHONY-5.5.0/SYMPHONY/Applications/MATCH/src/Master/user_main.c:80

The problem appears to be that "user" is null, and gets dereferenced.  I tried crawling up the stack, and it remains null at least until sym_solve() (frame #7 above), at which point I kindof got lost between env and tm and so on.  I've no prior experience with SYMPHONY-I just downloaded it today, so not really sure at what point user ought to have been set or why it might not have been.  I did notice there were some get/set routines in master.c that check if it's null, so presumably those weren't used.

I had similar results with the VRP application, though of course the details were different.

This seems like a bug unlikely to have gone unnoticed in development, so perhaps it's a build or installation issue?  The solver itself seems to run fine, however, and if the applications were unable to find the libraries, I shouldn't expect to get this far.

**Comment by svigerske** [comment]
Comment by hhecht created at 2013-07-29 02:21:52

I've built and tested 5.4.4 successfully, so I guess it may be a bug, rather than an installation/build error, after all.  I can try to bisect the bug if that would be helpful, but I'll wait until I hear from someone before doing so, as this may prove to be a simple problem for someone familiar with the software.

Sorry for the formatting in the initial report: I wasn't expecting Trac to do anything fancier than accept and post plain text.  I can repost the backtrace if necessary.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2013-07-29 18:39:23

Changing assignee from menal to @tkralphs.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2013-07-29 18:39:23

Changing status from new to assigned.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2013-07-29 18:40:33

I have replicated this and I'm working on a fix.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2013-08-03 13:29:00

This is fixed and there is a new release 5.5.1. The problem was that local branching calls the solver recursively. In the case of an application with user callbacks, this was not working because the user data structure was not passed in. For now, local branching has been disabled with applications.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2013-08-03 14:25:44

Resolution: fixed
